name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: |
        cd aplikacija/backend
        npm install

    - name: Run Tests
      env:
        NODE_ENV: test # Use SQLite in testing
      run: |
        cd aplikacija/backend
        npm test
