name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Docker
      run: |
        docker-compose -f aplikacija/backend/docker-compose.yml up -d
        docker ps

    - name: Wait for MySQL
      run: |
        until docker exec my_mysql mysqladmin ping -h127.0.0.1 --silent; do
          echo "Waiting for MySQL to be ready..."
          sleep 3
        done

    - name: Install Dependencies
      run: |
        cd aplikacija/backend
        npm install

    - name: Run Tests
      run: |
        cd aplikacija/backend
        npm test

    - name: Tear Down Docker
      if: always()
      run: |
        docker-compose -f aplikacija/backend/docker-compose.yml down
