name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install
        working-directory: aplikacija/backend

      - name: Start Backend Server
        run: npm start &
        working-directory: aplikacija/backend

      - name: Wait for Backend to Start
        run: sleep 10

      - name: Run Tests
        run: npm test
        working-directory: aplikacija/backend

      - name: Build Docker Image
        run: docker build -t your-dockerhub-username/backend:latest .
        working-directory: aplikacija

      - name: Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push your-dockerhub-username/backend:latest
