name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: projectdb
          MYSQL_USER: projectuser
          MYSQL_PASSWORD: projectpass123
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install
        working-directory: aplikacija/backend

      - name: Ensure `.env` File is Available
        run: |
          echo "Checking if .env exists"
          ls aplikacija/backend
          cat aplikacija/backend/.env
        shell: bash

      - name: Start Backend Server
        run: |
          npm start &
        working-directory: aplikacija/backend

      - name: Wait for Backend to Start
        run: sleep 10

      - name: Run Backend Tests
        run: npm test
        working-directory: aplikacija/backend/tests

      - name: Build Backend Docker Image
        run: docker build -t your-dockerhub-username/backend:latest .
        working-directory: aplikacija/backend

      - name: Push Backend Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push your-dockerhub-username/backend:latest
