name: Frontend CI/CD

on:
  push:
    branches:
      - main
      - production

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install
        working-directory: aplikacija

      - name: Run Specific Tests
        run: npx jest src/vaja4funk.test.js --passWithNoTests
        working-directory: aplikacija

      - name: Build Application
        run: npm run build
        working-directory: aplikacija

      - name: Build Docker Image
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            TAG="dev"
          elif [[ "${{ github.ref }}" == "refs/heads/production" ]]; then
            TAG="prod"
          fi
          docker build -t vitopolenek/frontend-image:$TAG .
          echo "TAG=$TAG" >> $GITHUB_ENV
        working-directory: aplikacija

      - name: Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push vitopolenek/frontend-image:${{ env.TAG }}

    environment:
      name: ${{ github.ref == 'refs/heads/production' && 'Production' || 'Development' }}
