name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install
        working-directory: aplikacija

      - name: Run Specific Tests
        run: npm test --src/vaja4funk.test.js
        working-directory: aplikacija

      - name: Build Application
        run: npm run build
        working-directory: aplikacija

      - name: Build Docker Image
        run: docker build -t vitopolenek/frontend-image:latest .
        working-directory: aplikacija

      - name: Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push vitopolenek/frontend-image:latest
