name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install
        working-directory: ./aplikacija

      - name: Run Specific Tests and Generate Coverage
        run: |
          npx jest src/vaja4funk.test.js --coverage --passWithNoTests
        working-directory: ./aplikacija

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./aplikacija
          args: >
            -Dsonar.organization=vitoopolenek
            -Dsonar.projectKey=vitoopolenek_rirsvaja
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**,**/dist/**
